# Подключаем локальные настройки сборки.
include Makefile.local

## Папка с composer.json (htdocs)
COMPOSER_ROOT_DIR := $(PUBLIC_DIR)

ifneq ($(realpath tools/dev-tools/make),)
# Подключаем нужные библиотеки.
include tools/dev-tools/make/common.mk
include tools/dev-tools/make/npm.mk
include tools/dev-tools/make/composer.mk
include tools/dev-tools/make/remote.mk
include tools/dev-tools/make/db.mk
#include tools/dev-tools/make/wordpress.mk
endif

## Папка темы оформления.
theme_dir := $(PUBLIC_DIR)/themes/customized

.PHONY: build
build: ## Собирает изменившиеся файлы (цель по умолчанию).
# dev-tools должны устанавливаться в отдельном процессе, чтобы после Makefile был перечитан
# заново для подключения библиотек.
	$(MAKE) tools/dev-tools/.git
	$(MAKE) node_modules scripts styles

.PHONY: clean
clean: composer-clean npm-clean ## Очищает проект от созданных файлов.

.PHONY: scripts
scripts: $(uglifyjs) ## Собирает сценарии.
	$(call run-uglifyjs,$(theme_dir)/main.js,$(theme_dir)/main.min.js)

.PHONY: styles
styles: $(sass) ## Собирает стили.
	$(call run-sass,$(theme_dir)/bundle.scss,$(theme_dir))

.PHONY: update
update: ## Обновляет зависимости проекта.
	cd tools/dev-tools && git pull
#	$(MAKE) npm-update
#	$(MAKE) composer-update

## Устанавливает dev-tools.
tools/dev-tools/.git:
	git submodule init
	git submodule update
